### PR TITLE
Define an error for a failed (return status != 200) request to the IDP.

### PR DESCRIPTION
**Pull request by nawatts**
If an incorrect password or other reason causes a non 200 response
from the IDP, the response may not be valid XML. If the IDP's ECP
endpoint is protected by Apache, it may send an HTML response.
Previously in that case, the error returned by login would be an XML
parser error. However, the root cause of the error is that the
request to the IDP was not successful. See #5.

### CODE REVIEW

**Comment by tptee** [comment]
LGTM after those little comments!

I'll make an issue for factoring out the XML error checking into responseXML() in `Alamofire+ReactiveCocoa.swift` down the road.

**Comment by nawatts** [comment]
I'm not sure how you want to handle responseXML. The issue with the IDP request is that (in some cases anyway) it returns XML if successful and HTML if it fails. The responseXML method is fine as is if the requested URL could be counted on to always return XML. And really, it works ok in this case too. It's just that invalid XML doesn't accurately describe the root cause of the error.

**Comment by tptee** [comment]
I was thinking that the ReactiveCocoa extensions could handle bad status codes, both for responseString() and responseXML() (doesn't look like they do currently). Thoughts?

**Comment by nawatts** [comment]
Practically for this, agreed. Ideally, I think I would prefer something like `request->requireSuccess->responseXML`. I could see the case where you would want to get the returned XML regardless of what the status code is.

**Comment by tptee** [comment]
I dig it :+1:

**Comment by nawatts** [comment]
Weak/unowned can't be used on structs. But I think it's not an issue because the closure containing self isn't being stored as a property on ECP.

**Pull request merged**
